### PR TITLE
WIP baseline from Robert

### PR DESCRIPTION
**Pull request by rburckner**
Lots of formatting.

Most significant 
- Better code quality
- added session management features with Redis and Session File Store.
- added photo collection to DB

### CODE REVIEW

**Comment by dan-online** [comment]
Also in the terminal I see this error:

```bash
ReferenceError: /Users/DanCodes/Desktop/Code/test-spruce/views/error.ejs:17
    15|   <link rel="stylesheet" type="text/css" href="/stylesheets/moment.css">
    16|   <body>
 >> 17|   <%- include('navbar')	-%>
    18| 
    19|   <div class="container" id="mainPage">
    20|   	<h2><%= message %></h2>

/Users/DanCodes/Desktop/Code/test-spruce/views/navbar.ejs:5
    3|     <h2>
    4|       <img src="/images/logo/logo.png" class="logo">
 >> 5|       <%= title %>
    6|     </h2>
    7|     </a>
    8|     <div class="float-right margin-top-20">

title is not defined
```
@rburckner set app.locals.title in a middleware so its global

**Comment by dan-online** [comment]
Something else is that images won't load
```bash
GET /api/v1/file/5d6d456f65a7e0fa480d92fd-banner.png 404 136 - 3.521 ms
```

**Comment by rburckner** [comment]
> Is electron needed? I don't think we are currently using it.

idk what it is for. I haven't pulled out everything yet. I am still learning from what you all have.

**Comment by rburckner** [comment]
> Also in the terminal I see this error:
> 
> ```shell
> ReferenceError: /Users/DanCodes/Desktop/Code/test-spruce/views/error.ejs:17
>     15|   <link rel="stylesheet" type="text/css" href="/stylesheets/moment.css">
>     16|   <body>
>  >> 17|   <%- include('navbar')	-%>
>     18| 
>     19|   <div class="container" id="mainPage">
>     20|   	<h2><%= message %></h2>
> 
> /Users/DanCodes/Desktop/Code/test-spruce/views/navbar.ejs:5
>     3|     <h2>
>     4|       
>  >> 5|       <%= title %>
>     6|     </h2>
>     7|     </a>
>     8|     <div class="float-right margin-top-20">
> 
> title is not defined
> ```
> 
> @rburckner set app.locals.title in a middleware so its global

Im not sure. Mine runs fine.

Does app.js contain: 
  res.status(err.status || 500);
  res.render('error', {
    title: req.app.conf.name,
  });

near line 130?

**Comment by rburckner** [comment]
Yikes, app.js isn't correct

**Comment by dan-online** [comment]
Chat seems to have dissapeared from the sidebar?

**Comment by dan-online** [comment]
Also when making myself a developer the option doesn't check when I reload in /me

**Comment by rburckner** [comment]
That wasn't me. I don't think. LolOn Sep 2, 2019 20:57, DanCodes <notifications@github.com> wrote:Chat seems to have dissapeared from the sidebar?

**Comment by rburckner** [comment]
It's still a work in progress :)On Sep 2, 2019 19:39, DanCodes <notifications@github.com> wrote:Something else is that images won't load
GET /api/v1/file/5d6d456f65a7e0fa480d92fd-banner.png 404 136 - 3.521 ms

**Comment by rburckner** [comment]
I had observed the same thing. What's the purpose of the developer option?On Sep 2, 2019 20:59, DanCodes <notifications@github.com> wrote:Also when making myself a developer the option doesn't check when I reload in /me

**Comment by dan-online** [comment]
> That wasn't me. I don't think. LolOn Sep 2, 2019 20:57, DanCodes <notifications@github.com> wrote:Chat seems to have dissapeared from the sidebar? —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

Hmm I only see it in your fork

**Comment by dan-online** [comment]
> It's still a work in progress :)On Sep 2, 2019 19:39, DanCodes <notifications@github.com> wrote:Something else is that images won't load GET /api/v1/file/5d6d456f65a7e0fa480d92fd-banner.png 404 136 - 3.521 ms —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

Yea this works now so thats good

**Comment by dan-online** [comment]
> I had observed the same thing. What's the purpose of the developer option?On Sep 2, 2019 20:59, DanCodes <notifications@github.com> wrote:Also when making myself a developer the option doesn't check when I reload in /me —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

Its to allow developers to post, get posts and use spruce as just the backend system

**Comment by DivySrivastava** [comment]
Maybe he had forked it before we added the chat feature.

**Comment by dan-online** [comment]
> Maybe he had forked it before we added the chat feature.

When I go to /chat It all works

**Comment by DivySrivastava** [comment]
Hmm Weird

**Comment by DivySrivastava** [comment]
Well @rburckner, Oak can be replaced with Spruce. I guess.

**Comment by dan-online** [comment]
@rburckner would you say this is ready to be merged?

**Comment by DivySrivastava** [comment]
Is the developer check option on /me working now? @dan-online

**Comment by dan-online** [comment]
>Is the developer check option on /me working now? @dan-online

@DivySrivastava I will check later

**Pull request closed without merging**
