### PR TITLE
Rewrite PR

### PR DESCRIPTION
**Pull request by dan-online**
# What this will do
 - ~Move socket init!~
 -  ~Use session middleware~
 - ~Add one-one chat between users~
 - ~Add a public **api**~
 - ~Activity tab with real-time notifications~
 - ~Add lazy-blur load for images~

### CODE REVIEW

**Comment by DivySrivastava** [comment]
We can implement this...
https://github.com/sivasankars/private-chat-application

**Comment by DivySrivastava** [comment]
Pushed all that we did...
Finally

**Comment by dan-online** [comment]
@DivySrivastava now all thats left is public api and activity tab

**Comment by DivySrivastava** [comment]
@dan-online We will need to add a `Spruce for developers` feature for ppl to obtain the API key and access it. Any suggestions?

**Comment by dan-online** [comment]
> @dan-online We will need to add a `Spruce for developers` feature for ppl to obtain the API key and access it. Any suggestions?

Want to create a website for it?

**Comment by DivySrivastava** [comment]
@dan-online Yeah...a one-page documentation and API-key generation website will be more than enough.

**Comment by dan-online** [comment]
Yea I agree, something like a git-book thingy

**Comment by dan-online** [comment]
Ill try and do that today @DivySrivastava

**Pull request merged**
