### PR TITLE
Settings api

### PR DESCRIPTION
**Pull request by MayorChano**
@DivySrivastava on save the user at front end loses all settings until relogin. Very weird

### CODE REVIEW

**Comment by DivySrivastava** [comment]
Great..I didn't notice the issue

**Comment by DivySrivastava** [comment]
Umm..maybe you forgot to destroy and then re-assign session cookies...

**Comment by DivySrivastava** [comment]
@MayorChano See https://github.com/dan-divy/spruce/commit/e4b0ca9c6b2fd341df086958aa56413893b668f7

**Comment by MayorChano** [comment]
Oh wow, why do we need to do that?

**Comment by DivySrivastava** [comment]
The session cookie still has the previous profile data after the profile is changed..
So we need to update the cookies with the new updated profile

**Comment by MayorChano** [comment]
Oh ok I got it

**Pull request merged**
