### PR TITLE
WIP Oak Merge

### PR DESCRIPTION
**Pull request by rburckner**

### CODE REVIEW

**Comment by DivySrivastava** [comment]
@dan-online Should we modify our front-end to use Angular.js? It could be useful in smooth page routing.

**Comment by DivySrivastava** [comment]
We should use YAML instead of json for the config. It will be helpful for non-technical people to host their own instance.

**Comment by rburckner** [comment]
abandoned 'Oak'

**Comment by dan-online** [comment]
> @dan-online Should we modify our front-end to use Angular.js? It could be useful in smooth page routing.

Yea sounds like a good idea

**Comment by rburckner** [comment]
I'm indifferent. Even .env files are simple. On Sep 2, 2019 15:12, Divy Srivastava <notifications@github.com> wrote:We should use YAML instead of json for the config. It will be helpful for non-technical people to host their own instance.

**Comment by rburckner** [comment]
You can. I'd have to learn it.On Sep 2, 2019 18:20, DanCodes <notifications@github.com> wrote:
@dan-online Should we modify our front-end to use Angular.js? It could be useful in smooth page routing.

Yea sounds like a good idea

**Pull request closed without merging**
