### PR TITLE
Persist images using cloudinary

### PR DESCRIPTION
**Pull request by universallythinking**
I edited ROUTES/API/V1/INDEX.JS and ROUTES/SETTINGS.JS and added CONFIG/CLOUDINARY.JS so that images persist.

### CODE REVIEW

**Comment by divy-work** [comment]
@universallythinking TYSM, there are merge conflicts with the master branch, could you please resolve them?

(cc @dan-online)

**Comment by dan-online** [comment]
Looks good, as @divy-work said, there are some merge conflicts so it would be great if you could resolve those first

**Comment by dan-online** [comment]
Also can you make cloudinary optional, if someone does not wish to use it or doesn't have it setup, pfp upload errors.

**Comment by universallythinking** [comment]
I'm not seeing any conflicts, but I could be missing something...  Cloudinary is now optional, with env variables.

**Comment by dan-online** [comment]
image

Here are the merge conflicts

**Comment by universallythinking** [comment]
Screen Shot 2020-06-27 at 3 50 02 PM

It doesn't look like I have those permissions...

**Comment by universallythinking** [comment]
Give me a sec

**Comment by universallythinking** [comment]
Should be good to go...

**Comment by divy-work** [comment]
LGTM, Merging...

**Pull request merged**
